name = "Seymour"
defaultTargets = ["Seymour"]

[leanOptions]
autoImplicit = false
relaxedAutoImplicit = false
pp.structureInstances = false
pp.numericProj.prod = false

[[require]]
name = "linters"
git = "https://github.com/madvorak/leanters"
rev = "main"

[[lean_lib]]
name = "Seymour"
