name = "Seymour"
defaultTargets = ["Seymour"]

[leanOptions]
autoImplicit = false
relaxedAutoImplicit = false
pp.structureInstances = false
pp.numericProj.prod = false

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "v4.16.0"

[[require]]
name = "checkdecls"
git = "https://github.com/PatrickMassot/checkdecls.git"

[[require]]
name = "«doc-gen4»"
git = "https://github.com/leanprover/doc-gen4"
rev = "main"

[[lean_lib]]
name = "Seymour"
