name = "Seymour"
defaultTargets = ["Seymour"]

[leanOptions]
autoImplicit = false
relaxedAutoImplicit = false
pp.structureInstances = false
pp.numericProj.prod = false

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "stable"

[[lean_lib]]
name = "Seymour"
